---
title: "Tut2"
author: "Jerry Lu (Yen-Chia Lu)"
format: pdf
---
```{r}
install.packages("usethis")
library(usethis)
create_github_token()
```

```{r}
install.packages("gitcreds")
library(gitcreds)
gitcreds_set()
```


```{r}
#### Preamble ####
# Purpose: Get data on 2021 Toronto shelter usage and make table
# Author: Jerry Lu (Yen-Chia Lu)
# Email: jerry33692@gmail.com
# Date: 15 January 2024

```


```{r}
library("janitor")
library("opendatatoronto")
library("tidyverse")
library("knitr")
```

```{r}
#### Acquire ####
toronto_shelters <-
  # Each package is associated with a unique id  found in the "For 
  # Developers" tab of the relevant page from Open Data Toronto
  # https://open.toronto.ca/dataset/daily-shelter-overnight-service-occupancy-capacity/
  list_package_resources("21c83b32-d5a8-4106-a54f-010dbe49f6f2") |>
  # Within that package, we are interested in the 2021 dataset
  filter(name == 
    "daily-shelter-overnight-service-occupancy-capacity-2021.csv") |>
  # Having reduced the dataset to one row we can get the resource
  get_resource()
```

```{r}
toronto_shelters_clean <-
  clean_names(toronto_shelters) |>
  mutate(occupancy_date = ymd(occupancy_date)) |> 
  select(occupancy_date, occupied_beds)

head(toronto_shelters_clean)
```

```{r}
toronto_shelters_clean2 <-toronto_shelters_clean |>
  mutate(occupancy_month = month(
    occupancy_date,
    label = TRUE,
    abbr = FALSE
  )) |>
  arrange(month(occupancy_date)) |> 
  drop_na(occupied_beds) |> 
  summarise(number_occupied = mean(occupied_beds),
            .by = occupancy_month) 

toronto_shelters_clean2 |>
  ggplot(aes(x = occupancy_month,  y = number_occupied)) +
  geom_point() 
```



